version: '3.8'

services:
  app:
    build:
      context: .
      target: builder 
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm exec vite-node src/server.ts
    env_file:
      - .env